### ISSUE TITLE
fix compiler warning in psci_set_req_local_pwr_state

### ISSUE THREAD

**Issue by sbranden** [ARM-software/tf-issues#379] opened 2016-03-23 20:01 UTC
latest GCC compiler produces a warning fixed by adding the following assert:
	assert(pwrlvl <= PSCI_MAX_PWR_LVL);

**Comment by danh-arm** [comment] 2016-03-29 16:04
This looks like a duplicate of #347

**Comment by danh-arm** [comment] 2016-04-18 11:11
Closing as I'm assuming this is a duplicate (which is now fixed). Please re-raise if necessary.

**Closed by danh-arm** 2016-04-18 11:11 UTC
Labels: bug
